name: service2

on:
  push:
    branches: [ main ]
    paths:
      - pom.xml
      - services/pom.xml
      - services/service2/**
      - security/**
      - .github/workflows/service2.yml

jobs:
  run:
    uses: ./.github/workflows/service-workflow.yml
    with:
      service: service2