name: service1

on:
  push:
    branches: [ main ]
    paths:
      - pom.xml
      - services/pom.xml
      - services/service1/**
      - security/**
      - .github/workflows/service1.yml

jobs:
  run:
    uses: ./.github/workflows/service-workflow.yml
    with:
      service: service1
